// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {oui} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Search(arg1:string):Promise<oui.OUI>;
